//MESSAGE ACTIONS
export const SAVE_MESSAGE_SUCCESS = 'SAVE_MESSAGE_SUCCESS';
export const RECEIVE_MESSAGE_SUCCESS = 'RECEIVE_MESSAGE_SUCCESS';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const CLEAR_MESSAGES_SUCCeSS = 'CLEAR_MESSAGES_SUCCESS';

//USER ACTIONS
//export const LOGGED_ADMIN_SUCCESS = 'LOGGED_ADMIN_SUCCESS';
export const CHECKED_ADMIN_SUCCESS = 'CHECKED_ADMIN_SUCCESS';
export const LOAD_GUESTS_SUCCESS = 'LOAD_GUESTS_SUCCESS';
export const GET_GUESTS_SUCCESS = 'GET_GUESTS_SUCCESS';

//SOCKET ACTIONS
export const INITIALIZE_SOCKET_SUCCESS = 'INITIALIZE_SOCKET_SUCCESS';