//MESSAGE ACTIONS
export const SAVE_MESSAGE_SUCCESS = 'SAVE_MESSAGE_SUCCESS';
export const RECEIVE_MESSAGE_SUCCESS = 'RECEIVE_MESSAGE_SUCCESS';
export const LOAD_MESSAGES_SUCCESS = 'LOAD_MESSAGES_SUCCESS';
export const CLEAR_MESSAGES_SUCCESS = 'CLEAR_MESSAGES_SUCCESS';

//USER ACTIONS
//export const LOGGED_ADMIN_SUCCESS = 'LOGGED_ADMIN_SUCCESS';
export const CHECKED_ADMIN_SUCCESS = 'CHECKED_ADMIN_SUCCESS';
export const LOAD_GUESTS_SUCCESS = 'LOAD_GUESTS_SUCCESS';
export const GET_GUESTS_SUCCESS = 'GET_GUESTS_SUCCESS';

//SOCKET ACTIONS
export const INITIALIZE_SOCKET_SUCCESS = 'INITIALIZE_SOCKET_SUCCESS';

//SCHEDULE ACTIONS
export const LOAD_SCHEDULES_SUCCESS = 'LOAD_SCHEDULES_SUCCESS';
export const UPDATE_SCHEDULE_SUCCESS = 'EDIT_SCHEDULE_SUCCESS';
export const SAVE_SCHEDULE_SUCCESS = 'SAVE_SCHEDULE_SUCCESS';
export const DELETE_SCHEDULE_SUCCESS = 'DELETE_SCHEDULE_SUCCESS';

//events ACTIONS
export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const SAVE_EVENT_SUCCESS = 'SAVE_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';

//events ACTIONS
export const LOAD_ANNOUNCEMENTS_SUCCESS = 'LOAD_ANNOUNCEMENTS_SUCCESS';
export const SAVE_ANNOUNCEMENT_SUCCESS = 'SAVE_ANNOUNCEMENT_SUCCESS';
export const UPDATE_ANNOUNCEMENT_SUCCESS = 'UPDATE_ANNOUNCEMENT_SUCCESS';
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';

